dataset: ../1特征提取/feature_2.csv #此处采用相对路径，两个..代表上级目录
group_clolumn: group
group_file: group.csv #不在同一文件夹需要写完整路径
label_clolumn: label
#------------以上是必须填的参数-----------------

#------------以下都是可选填的参数-----------------
pvaule: 0.005
corr_method: pearson #kendall,spearman

